# Generated by Django 4.0.2 on 2022-04-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('sitename', models.CharField(max_length=100)),
                ('siteaddress', models.CharField(max_length=200)),
                ('utillityname', models.CharField(max_length=45)),
                ('category', models.CharField(blank=True, max_length=45)),
                ('emailaddress', models.CharField(max_length=45)),
                ('contact_name', models.CharField(max_length=45)),
                ('phone_no', models.BigIntegerField(null=True)),
                ('sitetype', models.CharField(max_length=45)),
                ('pvdesc', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Companys',
            },
        ),
        migrations.CreateModel(
            name='Company_resiliency_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criticalload', models.CharField(blank=True, max_length=50)),
                ('noofoutages', models.CharField(blank=True, max_length=50)),
                ('outageduration', models.CharField(blank=True, max_length=50)),
                ('outageType', models.CharField(blank=True, max_length=50)),
                ('othertype', models.CharField(blank=True, max_length=50)),
                ('powerfailureimpact', models.CharField(blank=True, max_length=500)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='companys.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Company_new_ev_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_req_evchargers', models.IntegerField()),
                ('charger_type', models.CharField(max_length=50)),
                ('EVcharge', models.CharField(max_length=50)),
                ('visiting_vehicles', models.CharField(max_length=50)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='companys.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Company_load_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaddata', models.FileField(upload_to='')),
                ('pdfbills', models.FileField(upload_to='')),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companys.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Company_existing_pv_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('existingpvsize', models.IntegerField()),
                ('existingpvtype', models.CharField(max_length=45)),
                ('solarGenerationdata', models.FileField(default=0, upload_to='')),
                ('systemSLD', models.FileField(default=0, upload_to='')),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='companys.company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Company_existing_ev_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_existingevs', models.CharField(max_length=50)),
                ('no_of_existingevchargers', models.IntegerField()),
                ('existingevdesc', models.CharField(max_length=500)),
                ('annual_ev_miles', models.IntegerField()),
                ('annual_fuel_expenditure', models.IntegerField()),
                ('desired_ev_details', models.CharField(max_length=500)),
                ('additionalInformation', models.CharField(max_length=500)),
                ('no_of_req_evchargers', models.IntegerField()),
                ('charger_type', models.CharField(max_length=50)),
                ('EVcharge', models.CharField(max_length=50)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='companys.company', verbose_name='Company')),
            ],
        ),
    ]
